# Generated by Django 3.2.9 on 2022-04-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='iCategory',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='icategory',
        ),
    ]
